export let companies = [
  {name: 'بازار', url: 'https://careers.cafebazaar.ir/', image: 'images/companies/bazar.png', caption: 'بازار'},
  {name: 'دیوار', url: 'https://careers.divar.ir', image: 'images/companies/divar.jpg', caption: 'دیوار'},
  {name: 'بلد', url: 'https://careers.balad.ir', image: 'images/companies/balad.png', caption: 'بلد'},
  {name: 'نشان', url: 'https://neshan.org/life/jobs', image: 'images/companies/neshan.png', caption: 'نشان'},
  {name: 'علی بابا', url: 'https://www.alibaba.ir/jobs', image: 'images/companies/alibaba.png', caption: 'علی بابا'},
  {name: 'اسنپ', url: 'https://career.snapp.ir', image: 'images/companies/snapp.jpg', caption: 'اسنپ'},
  {name: 'تپسی', url: 'https://careers.tapsi.ir', image: 'images/companies/tapsi.png', caption: 'تپسی'},
  {name: 'دیجی کالا', url: 'https://careers.digikala.com', image: 'images/companies/digikala.jpg', caption: 'دیجی کالا'},
  {name: 'همکاران سیستم', url: 'https://www.systemgroup.net/jobs', image: 'images/companies/hamkaran.jpg', caption: 'همکاران سیستم'},
  {name: 'داتین', url: 'https://job.dotin.ir/', image: 'images/companies/dotin.jpeg', caption: 'داتین'},
  {name: 'توسن', url: 'https://www.tosan.com/career-opportunities', image: 'images/companies/tosan.png', caption: 'توسن'},
  {name: 'فناپ', url: 'https://jobs.fanap.ir/', image: 'images/companies/fanap.png', caption: 'فناپ'},
  {name: 'طاقچه', url: 'https://taaghche.com/jobs', image: 'images/companies/taaghche.png', caption: 'طاقچه'},
  {name: 'فیدیبو', url: 'https://jobinja.ir/companies/fidibo/jobs', image: 'images/companies/fidibo.jpg', caption: 'فیدیبو'},
  {name: 'هفت هشتاد', url: 'https://jobinja.ir/companies/hafhashtad/jobs', image: 'images/companies/780.jpg', caption: 'هفت هشتاد'},
  {name: 'زومیت', url: 'https://www.zoomit.ir/hire', image: 'images/companies/zoomit.png', caption: 'زومیت'},
  {name: 'First Source', url: 'https://firstsource.tech/careers-at-firstsource', image: 'images/companies/firssource.jpeg', caption: 'First Source'},
  {name: 'یکتانت', url: 'https://www.yektanet.com/careers', image: 'images/companies/yektanet.jpg', caption: 'یکتانت'},
  {name: 'شیپور', url: 'https://careers.sheypoor.com', image: 'images/companies/sheypoor.jpg', caption: 'شیپور'},
  {name: 'ستون', url: 'https://careers.sotoon.ir', image: 'images/companies/sotoon.jpg', caption: 'ستون'},
];